---
development:
  cloud_name: hxezxbq2z
  api_key: '586127312275815'
  api_secret: OjwI9ZQqHtQqGv54RVFWT6y_1tg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hxezxbq2z
  api_key: '586127312275815'
  api_secret: OjwI9ZQqHtQqGv54RVFWT6y_1tg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hxezxbq2z
  api_key: '586127312275815'
  api_secret: OjwI9ZQqHtQqGv54RVFWT6y_1tg
  enhance_image_tag: true
  static_image_support: false
